build: false
environment:
  matrix:
  - TOXENV: "py27"
  - TOXENV: "py34"
  - TOXENV: "py35"
  - TOXENV: "py36"
  - TOXENV: "py37"
  - TOXENV: "pypy"
  - TOXENV: "docs"

matrix:
  allow_failures:
    - TOXENV: "pypy"

install:
  - echo Installed Pythons
  - dir c:\Python*

  - if "%TOXENV%" == "pypy" call scripts\install-pypy.bat

  - C:\Python37\python -m pip install tox

test_script:
  - C:\Python37\python -m tox
